
image:
  repository: registry.redhat.io/rhel8/postgresql-13
  tag: "1"

# fullnameOverride: postgresql

volume:
  size: 1Gi

service:
  port: 5432

resources: 
  limits:
    memory: 512Mi

postgresql:
  database: sampledb
  # user: 
  # password: 

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - node1.example.com

monitor: true