apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "httpd.fullname" . }}-cfg
data:
  status.conf: |
    <Location "/server-status">
        SetHandler server-status
        Require host localhost
    </Location>
