apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "httpd.fullname" . }}-init
data:
  {{- if .Values.certManager.enabled }}
  30-copy-certs-to-src.sh: |
    #!/bin/bash
    # This scripts moves config and src files to the target folder
    # They cannot be mounted directly, as there are mv and rm that
    # are not allowed on mounted ConfigMap/Secrets

    if [ -f /tmp/ssl/tls.crt ]; then
      mkdir -p ${HTTPD_APP_ROOT}/httpd-ssl/certs/
      cp /tmp/ssl/tls.crt ${HTTPD_APP_ROOT}/httpd-ssl/certs/server-cert.pem
    fi

    if [ -f /tmp/ssl/tls.key ]; then
      mkdir -p ${HTTPD_APP_ROOT}/httpd-ssl/private/
      cp /tmp/ssl/tls.key ${HTTPD_APP_ROOT}/httpd-ssl/private/server-key.pem
    fi

    # Removing indexes from root
    sed -ri 's/Options Indexes FollowSymLinks/Options -Indexes/g' ${HTTPD_MAIN_CONF_PATH}/httpd.conf
  {{- end }}
  60-config-log-json.sh: |
    #!/bin/bash
    # config_log_json() {
      sed -ri " s!^(\s*CustomLog\s+\S+\s+)combined!\1json!g;" ${HTTPD_MAIN_CONF_PATH}/httpd.conf
    # }
  90-init-git.sh: |
    #!/bin/bash
    #### This script cannot be injected in the image ####
    #### as the image does not contain command 'git' ####

    export HOME=/tmp

    set -x

    # Requires URL and target directory
    # REPO_URL="https://github.com/username/repository.git"
    TARGET_DIR="/var/www/html"

    # Check if the target directory exists
    if [ -e "$TARGET_DIR/index.html" ]; then
      # If the directory exists, navigate to it and perform a git pull
      cd "$TARGET_DIR"
      git config --global --add safe.directory /var/www/html
      git pull
    else
      # If the directory does not exist, clone the repository
      # As it is not allowed to clone if "lost+found" exists, we cannot do
      # git clone "$REPO_URL" -b "$REPO_BRANCH" "$TARGET_DIR"
      cd "$TARGET_DIR"
      git config --global --add safe.directory /var/www/html
      git init
      git remote add origin "$REPO_URL"
      git fetch
      git checkout -t origin/"$REPO_BRANCH"
    fi
