{{- if .Values.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}
{{- end }}