apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  name: {{ include "redis.fullname" . }}
stringData:
  database-password: {{ include "redis.password" . }}