apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL database server for development on OpenShift

type: application
kubeVersion: '>=1.24.0'
version: 0.1.2
appVersion: "1"

annotations:
  charts.openshift.io/name: PostgreSQL
  charts.openshift.io/provider: Community
  charts.openshift.io/providerType: Community

icon: https://www.postgresql.org/media/img/about/press/elephant.png

sources:
  - https://github.com/rgordill/openshift-helm-from-templates/charts
