apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ include "postgresql.fullname" . }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ include "postgresql.fullname" . }}
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: {{ include "postgresql.fullname" . }}
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ include "postgresql.fullname" . }}
       {{- if .Values.postgresql.logDestination }}
        - name: POSTGRESQL_LOG_DESTINATION
          value: {{ .Values.postgresql.logDestination }}
      {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: {{ include "postgresql.fullname" . }}-data
      {{- if .Values.monitor }}
      - name: envoy
        image: "docker.io/envoyproxy/envoy:contrib-v1.28-latest"
        imagePullPolicy: IfNotPresent
        ports:
          - name: admin
            containerPort: 8000
            protocol: TCP
          - name: listener
            containerPort: 15432
            protocol: TCP
        livenessProbe:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          httpGet:
            path: /
            port: admin
        readinessProbe:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          httpGet:
            path: /
            port: admin
        resources: {}
        volumeMounts:
        - mountPath: /etc/envoy/envoy.yaml
          name: envoy-conf
          subPath: envoy.yaml
        {{ end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "postgresql.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "postgresql.fullname" . }}
      {{- if .Values.monitor }}
      - name: envoy-conf
        configMap:
          defaultMode: 420
          name: {{ include "postgresql.fullname" . }}-envoy-conf
      {{ end }}