{{- if .Values.monitor }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-envoy-conf
data:
  envoy.yaml: |
    admin:
      access_log_path: /dev/null
      address:
        socket_address: { address: 0.0.0.0, port_value: 8000 }

    static_resources:
      clusters:
        name: postgres_cluster
        connect_timeout: 1s
        type: STRICT_DNS
        load_assignment:
          cluster_name: postgres_cluster
          endpoints:
            lb_endpoints:
              endpoint:
                address:
                  socket_address: { address: 127.0.0.1, port_value: 5432 }
      listeners:
        name: postgres_listener
        address:
          socket_address: { address: 0.0.0.0, port_value: 15432 }
        filter_chains:
          filters:
            - name: envoy.filters.network.postgres_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
                stat_prefix: egress_postgres
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp
                cluster: postgres_cluster
{{ end }}