apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{ include "postgresql.fullname" . }}
stringData:
  database-name: {{ .Values.postgresql.database }}
  database-password: {{ include "postgresql.password" . }}
  database-user: {{ include "postgresql.user" . }}
  database-admin-password: {{ include "postgresql.adminPassword" . }}