{{- if .Values.monitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  endpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
{{ end }}