apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.selectorLabels" . | nindent 8 }}
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
    - port: 9187
      targetPort: 9187
      protocol: TCP
      name: metrics
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}