apiVersion: v2
name: ipa-server
description: A Helm chart for FreeIPA server on OpenShift (https://github.com/freeipa/freeipa-container)

type: application
kubeVersion: '>=1.24.0'
version: 0.2.0
appVersion: "1"

annotations:
  charts.openshift.io/name: FreeIPA
  charts.openshift.io/provider: Community
  charts.openshift.io/providerType: Community

icon: https://avatars.githubusercontent.com/u/10979201

sources:
  - https://github.com/rgordill/openshift-helm-from-templates/charts
