apiVersion: v2
name: redis
description: A Helm chart for Redis in-memory data structure store for development on OpenShift

type: application
kubeVersion: '>=1.24.0'
version: 0.2.0
appVersion: "1"

annotations:
  charts.openshift.io/name: Redis
  charts.openshift.io/provider: Community
  charts.openshift.io/providerType: Community
  
icon: https://upload.wikimedia.org/wikipedia/commons/e/ee/Redis_logo.svg

sources:
  - https://github.com/rgordill/openshift-helm-from-templates/charts
