kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ipaServer.fullname" . }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}